### ISSUE TITLE
[Critical bug] Bt-Panel not running after updating to latest beta version

### ISSUE THREAD

**Issue by hungntv** [aaPanel/aaPanel#103]
I've just updated to latest beta version. Everything is OK excludes the Panel

Now I can't access to the Panel via public/private ip.

Please help me

Version
`aaPanel LinuxBeta 6.9.57 Release time: 2021/11/26`

Error
```
[root@instance-20211121-2058 ~]# service bt status
Bt-Panel not running
Bt-Task (pid 1631) already running
[root@instance-20211121-2058 ~]# service bt restart
Stopping Bt-Tasks...    done
Stopping Bt-Panel...    done
Starting Bt-Panel............failed
------------------------------------------------------
    app.secret_key = public.md5(str(os.uname())+str(psutil.boot_time()))
NameError: name 'psutil' is not defined
Traceback (most recent call last):
  File "/www/server/panel/BT-Panel", line 17, in <module>
    from BTPanel import app,sys,public
  File "/www/server/panel/BTPanel/__init__.py", line 60, in <module>
    app.secret_key = public.md5(str(os.uname())+str(psutil.boot_time()))
NameError: name 'psutil' is not defined
Traceback (most recent call last):
  File "/www/server/panel/BT-Panel", line 17, in <module>
    from BTPanel import app,sys,public
  File "/www/server/panel/BTPanel/__init__.py", line 60, in <module>
    app.secret_key = public.md5(str(os.uname())+str(psutil.boot_time()))
NameError: name 'psutil' is not defined
Traceback (most recent call last):
  File "/www/server/panel/BT-Panel", line 17, in <module>
    from BTPanel import app,sys,public
  File "/www/server/panel/BTPanel/__init__.py", line 60, in <module>
    app.secret_key = public.md5(str(os.uname())+str(psutil.boot_time()))
NameError: name 'psutil' is not defined
------------------------------------------------------
Error: BT-Panel service startup failed.
        done
Starting Bt-Tasks... Bt-Tasks (pid 20588 20589) already running
```

OS:
```
[root@instance-20211121-2058 ~]# uname -a
Linux instance-20211121-2058 5.4.17-2102.206.1.el8uek.aarch64 #2 SMP Wed Oct 6 17:35:01 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by hungntv** [comment]
edit file: /www/server/panel/BTPanel/__init__.py
add this line:
`import psutil`

Please fix this bug
