### ISSUE TITLE
How to deploy a Django Project

### ISSUE THREAD

**Issue by javierleonet** [aaPanel/aaPanel#138]
Hi,

Does someone how to deploy a Django Project in AAPanel?

I tried Python Maganer 2.0 but impossible for me!
I get this error when create a Project:

Sorry, something went wrong： Traceback (most recent call last): File "class/flask_sockets.py", line 30, in call handler, values = adapter.match() File "/www/server/panel/pyenv/lib/python3.7/site-packages/werkzeug/routing.py", line 1945, in match raise NotFound() werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

...and many others after that....

Please help me

![django](https://user-images.githubusercontent.com/28064422/188008139-f7a4a830-adcc-43b0-9cbb-7a82478d39a8.JPG)

**Comment by Anarbb** [comment]
the server you are trying to download dependencies from has missing pages "404 Error", it's not aapanels fault here

**Comment by javierleonet** [comment]
Thanks. 
Sorry, c an you explain to me wow to resolve this?. I'm new in this.

I would very much appreciate your help.
