### ISSUE TITLE
python app not autostarting, missing file /etc/rc.local

### ISSUE THREAD

**Issue by Dave-DuBois** [aaPanel/aaPanel#184]
App shows Auto Start = Open but when I click on Open I get a dialog to confirm and then I get this error:

Sorry, something went wrong：
Traceback (most recent call last):
File "class/panelPlugin.py", line 2142, in a
return eval(execStr)
File "", line 1, in
File "/www/server/panel/plugin/pythonmamager/pythonmamager_main.py", line 553, in edit_auto_start
self.set_auto_start()
File "/www/server/panel/plugin/pythonmamager/pythonmamager_main.py", line 569, in set_auto_start
if not re.search("pythonmamager_main\.py",rc_local):
File "/www/server/panel/pyenv/lib/python3.7/re.py", line 185, in search
return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

Steps to replicate:
It's a new install and setup:
os: Linux-6.2.0-1017-aws #17~22.04.1-Ubuntu SMP
Apache, UWSGI, Python 3.10, Django

config:
[uwsgi]
master = true
processes = 1
threads = 2
chdir = /www/wwwroot/[redacted]
wsgi-file= /www/wwwroot/[redacted]
http = 0.0.0.0:[redacted]
logto = /www/wwwroot/[redacted]/logs/error.log
chmod-socket = 660
vacuum = true
uid=www
gid=www
max-requests = 1000

**Comment by Dave-DuBois** [comment]
I followed the traceback and the file /etc/rc.local was missing from my install.  I created an empty file and now everything is running correctly.
