### ISSUE TITLE
Hi, my aaPanel is broken.  bt status Bt-Panel not running Bt-Task not running

### ISSUE THREAD

**Issue by nottellyou** [aaPanel/aaPanel#193]
OS: Debian 11.6

bt start
Starting Bt-Panel....	done
Starting Bt-Tasks... 	done

bt status
Bt-Panel not running
Bt-Task not running

ERROR:
tail /www/server/panel/logs/error.log
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/www/server/panel/BT-Panel", line 35, in <module>
    from BTPanel import app,sys,public
  File "/www/server/panel/BTPanel/__init__.py", line 33, in <module>
    import public
  File "class/public.py", line 408
    if uid != 1 or any(key in logMsg for key in ['default.db', 'public.py', 'users_main.py', 'config.py', '.jQuery.', '__init__.py', 'sysadmin']): return
     ^
SyntaxError: invalid syntax

bt version
Traceback (most recent call last):
  File "/www/server/panel/tools.py", line 20, in <module>
    import public,time,json
  File "/www/server/panel/class/public.py", line 408
    if uid != 1 or any(key in logMsg for key in ['default.db', 'public.py', 'users_main.py', 'config.py', '.jQuery.', '__init__.py', 'sysadmin']): return
     ^
SyntaxError: invalid syntax

The aaPanel version may be version 6 last.

What should I do to run aaPanel properly?

**Comment by nottellyou** [comment]
bt help
Traceback (most recent call last):
  File "/www/server/panel/tools.py", line 20, in <module>
    import public,time,json
  File "/www/server/panel/class/public.py", line 408
    if uid != 1 or any(key in logMsg for key in ['default.db', 'public.py', 'users_main.py', 'config.py', '.jQuery.', '__init__.py', 'sysadmin']): return
     ^
SyntaxError: invalid syntax

**Comment by aaPanel** [comment]
Please upgrade the panel to the latest version and restart again.
