### ISSUE TITLE
python定时占用100时间长

### ISSUE THREAD

**Issue by pudding1111** [aaPanel/aaPanel#195]
python定时占用100 ssh输入bt回车无反应 crtl+c会报python的错误，然后重装aapanel解决，接着循环往复。
root@VMHKNBBDIUCC:~# bt
^CTraceback (most recent call last):
  File "/www/server/panel/tools.py", line 20, in <module>
    import public,time,json
  File "/www/server/panel/class/public/__init__.py", line 14, in <module>
    from .common import *
  File "/www/server/panel/class/public/common.py", line 5, in <module>
    import gettext
  File "/www/server/panel/pyenv/lib/python3.12/gettext.py", line 73, in <module>
    _token_pattern = re.compile(r"""
                     ^^^^^^^^^^^^^^^
  File "/www/server/panel/pyenv/lib/python3.12/re/__init__.py", line 228, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/server/panel/pyenv/lib/python3.12/re/__init__.py", line 307, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/server/panel/pyenv/lib/python3.12/re/_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/server/panel/pyenv/lib/python3.12/re/_parser.py", line 979, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/server/panel/pyenv/lib/python3.12/re/_parser.py", line 460, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/server/panel/pyenv/lib/python3.12/re/_parser.py", line 535, in _parse
    continue
KeyboardInterrupt

**Comment by aaPanel** [comment]
Hi, this problem has been fixed by latest version. please upgrade your panel to latest.
