### ISSUE TITLE
Issue deleting old database backups

### ISSUE THREAD

**Issue by Timokirch** [aaPanel/aaPanel#201]
Hi team, i do see the following error in my environment:

```shell
[2024-10-01 14:15:02][DEBUG] - Traceback (most recent call last):
  File "/www/server/panel/class_v2/database_v2.py", line 1205, in DelBackup
    filename ＝ backup_info['filename']
               ~~~~~~~~~~~^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/www/server/panel/BTPanel/__init__.py", line 2545, in publicObject
    return run_exec().run(toObject, defs, get)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/server/panel/BTPanel/__init__.py", line 2491, in run
    result ＝ getattr(toObject, get.action)(get)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/server/panel/class_v2/database_v2.py", line 1222, in DelBackup
    (db_name, filename, str(ex)))
     ^^^^^^^
UnboundLocalError: cannot access local variable 'db_name' where it is not associated with a value
```

**Comment by Timokirch** [comment]
Nevermind - just found out that my centos is EOL

**Comment by aaPanel** [comment]
It's just occur on your centos, and what your centos release version?
