### ISSUE TITLE
Error in MongoDB Plugin: JSONDecodeError when Accessing Databases in MongoDB Settings

### ISSUE THREAD

**Issue by shahidx0x** [aaPanel/aaPanel#203]
**Description:**
When I attempt to access the database option in the MongoDB settings modal on aapanel, an error occurs, causing the database list to fail loading.

**Steps to Reproduce:**
1. Open aapanel on Ubuntu 22.04.5 LTS (x86_64, Python 3.12.3).
2. Navigate to the MongoDB plugin.
3. Click on the "Database" option in the MongoDB settings modal.
4. The following error occurs in the response.

**Expected Behavior:**
The MongoDB plugin should correctly load and display a list of available databases.

**Actual Behavior:**
An exception is raised due to a `JSONDecodeError`, preventing the plugin from displaying the database list.

**Error Details:**

```bash
REQUEST_DATE: 2024-10-17 10:25:02
VERSION: Ubuntu 22.04.5 LTS x86_64(Py3.12.3) - 7.0.10
REMOTE_ADDR: 118.179.116.241
REQUEST_URI: GET /plugin?action=a&name=mongodb&s=get_databases
REQUEST_FORM: {}
USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
Traceback (most recent call last):
  File "/www/server/panel/class/panelPlugin.py", line 2261, in a
    return public.run_plugin(get.name, get.s, get)
  File "/www/server/panel/class/public/common.py", line 8282, in run_plugin
    raise PanelError(res['msg'])
public.exceptions.PanelError: An error occurred while the panel was running: 
Traceback (most recent call last):
  File "/www/server/panel/plugin/mongodb/mongodb_main.py", line 19, in get_databases
    return json.loads(tmp)
  File "/www/server/panel/pyenv/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/www/server/panel/pyenv/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/www/server/panel/pyenv/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by aaPanel** [comment]
Thank you for your feedback. The issue has been fixed. You can resolve it by reinstalling this plugin.
