### ISSUE TITLE
CentOS 8 - DNS Manager

### ISSUE THREAD

**Issue by riiz0r** [aaPanel/aaPanel#40]
When I try to set the listening IP for the DNS Manager in aaPanel, I get the below error.

Traceback (most recent call last):
File "class/flask_sockets.py", line 30, in __call__
handler, values = adapter.match()
File "/www/server/panel/pyenv/lib/python3.7/site-packages/werkzeug/routing.py", line 1945, in match
raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "class/panelPlugin.py", line 1904, in a
return eval(execStr)
File "", line 1, in
File "plugin/dns_manager/dns_manager_main.py", line 189, in set_listen_ip
new_conf = re.sub(rep,"53 { "+values["listen_ip"],conf)
File "/www/server/panel/pyenv/lib/python3.7/re.py", line 194, in sub
return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

**Comment by riiz0r** [comment]
Nevermind! I reinstalled DNS Manager and it fixed its self.
