### ISSUE TITLE
Docker Manager not running!

### ISSUE THREAD

**Issue by can-acar** [aaPanel/aaPanel#58]
```

Sorry, something went wrong：
Traceback (most recent call last):
File "class/flask_sockets.py", line 30, in __call__
handler, values = adapter.match()
File "/www/server/panel/pyenv/lib/python3.7/site-packages/werkzeug/routing.py", line 1945, in match
raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/www/server/panel/pyenv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
chunked=chunked,
File "/www/server/panel/pyenv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/www/server/panel/pyenv/lib/python3.7/http/client.py", line 1277, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/www/server/panel/pyenv/lib/python3.7/http/client.py", line 1323, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/www/server/panel/pyenv/lib/python3.7/http/client.py", line 1272, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/www/server/panel/pyenv/lib/python3.7/http/client.py", line 1032, in _send_output
self.send(msg)
File "/www/server/panel/pyenv/lib/python3.7/http/client.py", line 972, in send
self.connect()
File "/www/server/panel/pyenv/lib/python3.7/site-packages/docker/transport/unixconn.py", line 46, in connect
sock.connect(self.unix_socket)
File "/www/server/panel/pyenv/lib/python3.7/site-packages/gevent/_socketcommon.py", line 628, in connect
raise _SocketError(result, strerror(result))
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/www/server/panel/pyenv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
timeout=timeout
File "/www/server/panel/pyenv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
File "/www/server/panel/pyenv/lib/python3.7/site-packages/urllib3/util/retry.py", line 531, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/www/server/panel/pyenv/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
raise value.with_traceback(tb)
File "/www/server/panel/pyenv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
chunked=chunked,
File "/www/server/panel/pyenv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/www/server/panel/pyenv/lib/python3.7/http/client.py", line 1277, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/www/server/panel/pyenv/lib/python3.7/http/client.py", line 1323, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/www/server/panel/pyenv/lib/python3.7/http/client.py", line 1272, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/www/server/panel/pyenv/lib/python3.7/http/client.py", line 1032, in _send_output
self.send(msg)
File "/www/server/panel/pyenv/lib/python3.7/http/client.py", line 972, in send
self.connect()
File "/www/server/panel/pyenv/lib/python3.7/site-packages/docker/transport/unixconn.py", line 46, in connect
sock.connect(self.unix_socket)
File "/www/server/panel/pyenv/lib/python3.7/site-packages/gevent/_socketcommon.py", line 628, in connect
raise _SocketError(result, strerror(result))
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "class/panelPlugin.py", line 1975, in a
return eval(execStr)
File "", line 1, in
File "plugin/docker/docker_main.py", line 663, in service_admin
for container in self.__docker.containers.list(all=True):
File "/www/server/panel/pyenv/lib/python3.7/site-packages/docker/models/containers.py", line 842, in list
since=since)
File "/www/server/panel/pyenv/lib/python3.7/site-packages/docker/api/container.py", line 192, in containers
res = self._result(self._get(u, params=params), True)
File "/www/server/panel/pyenv/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
return f(self, *args, **kwargs)
File "/www/server/panel/pyenv/lib/python3.7/site-packages/docker/api/client.py", line 191, in _get
return self.get(url, **self._set_request_timeout(kwargs))
File "/www/server/panel/pyenv/lib/python3.7/site-packages/requests/sessions.py", line 555, in get
return self.request('GET', url, **kwargs)
File "/www/server/panel/pyenv/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/www/server/panel/pyenv/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/www/server/panel/pyenv/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

```

**Comment by javadzanguei** [comment]
Can anyone answer this question?
